name: Release

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    name: Build - ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary: pdfshuff
          - name: Linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            binary: pdfshuff
          - name: macOS-x86_64
            os: macos-latest
            target: x86_64-apple-darwin
            binary: pdfshuff
          - name: macOS-aarch64
            os: macos-latest
            target: aarch64-apple-darwin
            binary: pdfshuff
          - name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            binary: pdfshuff.exe

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Install dependencies (Ubuntu)
        if: matrix.platform.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libatk1.0-dev

      - name: Install cross-compilation tools (Ubuntu ARM)
        if: matrix.platform.os == 'ubuntu-latest' && matrix.platform.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

      - name: Build
        run: cargo build --release --target ${{ matrix.platform.target }}

      - name: Rename binary
        run: |
          cd target/${{ matrix.platform.target }}/release
          if [ "${{ matrix.platform.os }}" = "windows-latest" ]; then
            cp ${{ matrix.platform.binary }} ../../../pdfshuff-${{ matrix.platform.name }}.exe
          else
            cp ${{ matrix.platform.binary }} ../../../pdfshuff-${{ matrix.platform.name }}
          fi
        shell: bash

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: pdfshuff-${{ matrix.platform.name }}${{ matrix.platform.os == 'windows-latest' && '.exe' || '' }}
